steps:
  # Step 1: Build the container image using Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
      - '--image=gcr.io/southern-list-427002-c2/gcr.io/southern-list-427002-c2/gcr.io/southern-list-427002-c2/github.com/munibshah/pythoncal:edc76f34445181db2244fcfedd1f33391290af11'
      - '--env=GOOGLE_BUILDABLE=./app.py'
      - '--env=GOOGLE_RUNTIME=python'

  # Step 2: Deploy the container image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rmgpgab-mstrainingcal-us-east4-munibshah-pythoncal--mawpd'
      - '--image'
      - 'gcr.io/southern-list-427002-c2/gcr.io/southern-list-427002-c2/github.com/munibshah/pythoncal:edc76f34445181db2244fcfedd1f33391290af11'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Remove this or modify it as necessary for your security requirements

# Images in Google Container Registry to be used for the build.
images:
  - 'gcr.io/southern-list-427002-c2/gcr.io/southern-list-427002-c2/github.com/munibshah/pythoncal:edc76f34445181db2244fcfedd1f33391290af11'
